=== MPEGGroup/FileFormatConformance/data/schemas/file-metadata.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Metadata scheme for contributed files",
  "type": "object",
  "properties": {
    "contributor": {
      "type": "string",
      "description": "Source of the file, e.g. company name"
    },
    "description": {
      "type": "string",
      "description": "Description of the file",
      "maxLength": 280
    },
    "md5": {
      "type": "string",
      "description": "MD5 checksum of the file"
    },
    "version": {
      "type": "integer",
      "description": "Version number of the file"
    },
    "published": {
      "type": "boolean",
      "default": false,
      "description": "Whether the file is published or not"
    },
    "associated_files": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^./.*$"
      },
      "description": "List of associated files"
    },
    "features": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "List of features as defined in the standard"
    },
    "notes": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "object"
        }
      ],
      "description": "Notes about the file"
    },
    "license": {
      "type": "string",
      "description": "License of the file"
    },
    "rel_filepath": {
      "type": "string",
      "pattern": "^./.*$",
      "description": "Relative path to the conformance file"
    },
    "mdms_number": {
      "anyOf": [
        { "type": "string", "pattern": "^m[0-9]+$" },
        {
          "type": "string",
          "maxLength": 0
        }
      ],
      "description": "MPEG Document Management System Number"
    },
    "conforms_to": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "ISO": {
            "type": "string",
            "description": "ISO number of the specification"
          },
          "version": {
            "type": "integer",
            "description": "Version of the specification"
          },
          "amendmends": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "minItems": 1
          },
          "corrigenda": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "minItems": 1
          }
        },
        "required": ["ISO", "version"]
      }
    }
  },
  "required": [
    "contributor",
    "description",
    "md5",
    "rel_filepath",
    "version",
    "published",
    "associated_files",
    "features",
    "license",
    "mdms_number",
    "conforms_to"
  ]
}

=== MPEGGroup/FileFormatConformance/data/file_features/published/heif/C025.json
{
  "contributor": "Nokia",
  "description": "A grid of 3x2 dimension. Uses the first 6 frames.",
  "md5": "a9c70c03464ca26748d851ba92e838af",
  "version": 2,
  "published": true,
  "associated_files": [],
  "features": [],
  "notes": {
    "bitstreams": {
      "B037": {
        "commit": "f17e517f7518984b4450349a88edc09519082c74",
        "description": "HEVC Main profile encoded bitstream made up of 20 frames (128x72 resolution)",
        "same_input_content": "B007",
        "url": "https://github.com/nokiatech/heif_conformance/blob/master/bitstreams/B037.265"
      }
    }
  },
  "license": "",
  "rel_filepath": "./C025.heic",
  "mdms_number": "m42431",
  "conforms_to": []
}

=== MPEGGroup/FileFormatConformance/data/file_features/published/heif/C023.json
{
  "contributor": "Nokia",
  "description": "A grid of 4 derived images which are cropped to (640,360)",
  "md5": "30f4de692c9b8fb04fa0bcf1c0cde365",
  "version": 2,
  "published": true,
  "associated_files": [],
  "features": [],
  "notes": {
    "bitstreams": {
      "B036": {
        "commit": "f17e517f7518984b4450349a88edc09519082c74",
        "description": "HEVC Main profile encoded bitstream made up of 20 frames (1280x720 resolution)",
        "same_input_content": "B004",
        "url": "https://github.com/nokiatech/heif_conformance/blob/master/bitstreams/B036.265"
      }
    }
  },
  "license": "",
  "rel_filepath": "./C023.heic",
  "mdms_number": "m42431",
  "conforms_to": []
}

=== MPEGGroup/FileFormatConformance/data/file_features/published/isobmff/a3-tone-protected.json
{
  "contributor": "Apple",
  "description": "Protected",
  "md5": "0ca4e979d1baabb89559d72be35ae372",
  "version": 1,
  "published": true,
  "associated_files": ["./a3c-prot-keys.txt"],
  "features": [
    "Ordinary box",
    "FTYP box",
    "Movie box",
    "video track",
    "audio track",
    "sync table",
    "Protected streams (basic)",
    "IOD box"
  ],
  "notes": "",
  "license": "",
  "rel_filepath": "./a3-tone-protected.mp4",
  "mdms_number": "",
  "conforms_to": []
}

=== MPEGGroup/FileFormatConformance/data/file_features/under_consideration/heif_single_stream_property_sstr/HEVC_1440x960_derived_image_SSTR.json
{
  "contributor": "Nokia",
  "description": "A file with SingleStreamProperty associated with overlay derived image item",
  "mdms_number": "m62051",
  "rel_filepath": "./HEVC_1440x960_derived_image_SSTR.heic",
  "associated_files": [],
  "version": 1,
  "md5": "00ec4328b48e4d9033bbbcc795ed416d",
  "published": false,
  "features": [],
  "conforms_to": [],
  "notes": "",
  "license": ""
}

=== MPEGGroup/FileFormatConformance/data/file_features/published/isobmff/14_large.json
{
  "contributor": "Telecom ParisTech",
  "description": "large",
  "md5": "39c2065af324c14b9752e5e000e0cd79",
  "version": 1,
  "published": true,
  "associated_files": [],
  "features": [
    "Ordinary box",
    "64-bit length",
    "FTYP box",
    "Free/skip",
    "Movie box",
    "normal' order (moov-mdat)",
    "track enabled bit",
    "video track",
    "64-bit chunks",
    "ctts offsets",
    "sync table",
    "Copyright box"
  ],
  "notes": {
    "compressed": true
  },
  "license": "",
  "rel_filepath": "./14_large.mp4.zip",
  "mdms_number": "",
  "conforms_to": []
}

=== MPEGGroup/FileFormatConformance/data/file_features/published/isobmff/restricted.json
{
  "contributor": "Ericsson",
  "description": "Restriced video",
  "md5": "f38f51702c2ffca5e2ce273f9f3230cb",
  "version": 1,
  "published": true,
  "associated_files": [],
  "features": [
    "Ordinary box",
    "FTYP box",
    "Free/skip",
    "Movie box",
    "late' order (mdat first)",
    "video track",
    "track fragment decode time",
    "sync table",
    "Level assignment",
    "Sub-tracks",
    "Restricted sample entry"
  ],
  "notes": "",
  "license": "",
  "rel_filepath": "./restricted.mp4",
  "mdms_number": "",
  "conforms_to": []
}

=== MPEGGroup/FileFormatConformance/data/file_features/under_consideration/cenc/video_cenc_128iv.json
{
  "contributor": "Telecom Paris",
  "description": "",
  "mdms_number": "m56755",
  "license": "",
  "md5": "fbd9b7a2e279c27f2f3535211e27d3d6",
  "rel_filepath": "./video_cenc_128iv.mp4",
  "version": 1,
  "published": false,
  "associated_files": ["./drm_cfg/cenc_128iv.xml"],
  "features": [],
  "notes": "",
  "conforms_to": []
}

=== MPEGGroup/FileFormatConformance/data/file_features/published/isobmff/FX-VY-9436R.3_qhd.json
{
  "contributor": "",
  "description": "",
  "md5": "f43027e041131c498ea6998400ee3f42",
  "version": 1,
  "published": true,
  "associated_files": ["./FX-VY-9436R.3_qhd.vinput.merged.xml"],
  "features": [],
  "notes": "",
  "license": "",
  "rel_filepath": "./FX-VY-9436R.3_qhd.mp4",
  "mdms_number": "",
  "conforms_to": []
}
