=== MPEGGroup/FileFormatConformance/data/schemas/file-metadata.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Metadata scheme for contributed files",
  "type": "object",
  "properties": {
    "contributor": {
      "type": "string",
      "description": "Source of the file, e.g. company name"
    },
    "description": {
      "type": "string",
      "description": "Description of the file",
      "maxLength": 280
    },
    "md5": {
      "type": "string",
      "description": "MD5 checksum of the file"
    },
    "version": {
      "type": "integer",
      "description": "Version number of the file"
    },
    "published": {
      "type": "boolean",
      "default": false,
      "description": "Whether the file is published or not"
    },
    "associated_files": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^./.*$"
      },
      "description": "List of associated files"
    },
    "features": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "List of features as defined in the standard"
    },
    "notes": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "object"
        }
      ],
      "description": "Notes about the file"
    },
    "license": {
      "type": "string",
      "description": "License of the file"
    },
    "rel_filepath": {
      "type": "string",
      "pattern": "^./.*$",
      "description": "Relative path to the conformance file"
    },
    "mdms_number": {
      "anyOf": [
        { "type": "string", "pattern": "^m[0-9]+$" },
        {
          "type": "string",
          "maxLength": 0
        }
      ],
      "description": "MPEG Document Management System Number"
    },
    "conforms_to": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "ISO": {
            "type": "string",
            "description": "ISO number of the specification"
          },
          "version": {
            "type": "integer",
            "description": "Version of the specification"
          },
          "amendmends": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "minItems": 1
          },
          "corrigenda": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "minItems": 1
          }
        },
        "required": ["ISO", "version"]
      }
    }
  },
  "required": [
    "contributor",
    "description",
    "md5",
    "rel_filepath",
    "version",
    "published",
    "associated_files",
    "features",
    "license",
    "mdms_number",
    "conforms_to"
  ]
}

=== MPEGGroup/FileFormatConformance/data/file_features/published/nalu/svc/mp4-live-LastTime-depRep-R1-0002.json
{
  "contributor": "",
  "description": "",
  "md5": "c36837424f0f2dd31aa259dc683d307a",
  "version": 1,
  "published": true,
  "associated_files": [],
  "features": [],
  "notes": "",
  "license": "",
  "rel_filepath": "./mp4-live-LastTime-depRep-R1-0002.mp4",
  "mdms_number": "",
  "conforms_to": []
}

=== MPEGGroup/FileFormatConformance/data/file_features/under_consideration/ex_in_trinsics/intrinsics/intrinsics.json
{
  "contributor": "Apple",
  "description": "Item 1:\n\tfx = 512\n\tfy = 512\n\ts = 0\n\tcx = 256\n\tcy = 96\n\tCoded as:\n\t\tflags: 6656\n\t\tValues: [33554432, 16777216, 8388608]\n\nItem 2:\n\tfx = 512\n\tfy = 501.5\n\ts = -100.5\n\tcx = 256\n\tcy = 96\n\tCoded as:\n\t\tflags: 72193\n\t\tValues: [33554432, 16777216, 8388608, 43821739, -201]\n\t",
  "mdms_number": "m62054",
  "rel_filepath": "./intrinsics.heic",
  "associated_files": [],
  "version": 1,
  "md5": "1a1ae259bbc7e71d2ac5e5cd36fd24ae",
  "published": false,
  "features": [],
  "conforms_to": [],
  "notes": "",
  "license": ""
}

=== MPEGGroup/FileFormatConformance/data/file_features/under_consideration/isobmff_nalu/isobmff_updates/sample_group_static_mapping.json
{
  "contributor": "Telecom Paris / CANON Research Centre France",
  "description": "Static mapping in sample group description box",
  "mdms_number": "m64279",
  "rel_filepath": "./sample_group_static_mapping.mp4",
  "associated_files": [],
  "version": 1,
  "md5": "534552507ffc6aceb4b3dff1a92f5b46",
  "published": false,
  "features": [],
  "conforms_to": [],
  "notes": "",
  "license": ""
}

=== MPEGGroup/FileFormatConformance/data/file_features/published/nalu/svc/mp4-live-LastTime-depRep-R3-0003.json
{
  "contributor": "",
  "description": "",
  "md5": "fdda90def0b51a11e3dc3be55351057c",
  "version": 1,
  "published": true,
  "associated_files": [],
  "features": [],
  "notes": "",
  "license": "",
  "rel_filepath": "./mp4-live-LastTime-depRep-R3-0003.mp4",
  "mdms_number": "",
  "conforms_to": []
}

=== MPEGGroup/FileFormatConformance/data/file_features/published/nalu/l-hevc/shvc_hev1_single_track.json
{
  "contributor": "Telecom ParisTech",
  "description": "L-HEVC Conformance (spatial and multiview layered)",
  "md5": "0a2c82a6850969b44c7529e954e673a1",
  "version": 1,
  "published": true,
  "associated_files": [],
  "features": [
    "video track",
    "Extractors",
    "Implicit Reconstruction",
    "oinf, linf and oref track reference"
  ],
  "notes": "",
  "license": "",
  "rel_filepath": "./shvc_hev1_single_track.mp4",
  "mdms_number": "",
  "conforms_to": []
}

=== MPEGGroup/FileFormatConformance/data/file_features/under_consideration/HEIF_progressive/progressive-focus.json
{
  "contributor": "Canon Research Centre France",
  "description": "Progressive focus rendering using 'prdi' and 'prgr'",
  "mdms_number": "m63202",
  "rel_filepath": "./progressive-focus.heic",
  "associated_files": [],
  "version": 1,
  "md5": "203b5b3c7d0283531470a77ebf768e1c",
  "published": false,
  "features": [],
  "conforms_to": [],
  "notes": "The progressive-focus.heic file, according to the \u2018prgr\u2019 entity group and the \u2018prdi\u2019 item properties stores the data with the thumbnail first, followed by the input images corresponding to the in-focus areas, and finishing with the remaining input images. The \u2018prgr\u2019 entity group and the \u2018prdi\u2019 item property indicate to a player that when realizing a progressive rendering of the grid, two intermediate reconstructions are of particular interest: a first preview of the primary item (the grid image item) using the thumbnail and an intermediate reconstruction (as shown on Figure 2) of the grid where the most interesting areas are displayed in high quality.",
  "license": ""
}

=== MPEGGroup/FileFormatConformance/data/file_features/published/nalu/svc/mp4-live-LastTime-depRep-R1-0001.json
{
  "contributor": "",
  "description": "",
  "md5": "e209b5c5db610d5969524a692a5e90c4",
  "version": 1,
  "published": true,
  "associated_files": [],
  "features": [],
  "notes": "",
  "license": "",
  "rel_filepath": "./mp4-live-LastTime-depRep-R1-0001.mp4",
  "mdms_number": "",
  "conforms_to": []
}

=== MPEGGroup/FileFormatConformance/data/file_features/under_consideration/cenc/audio_cbcs_const_iv.json
{
  "contributor": "Telecom Paris",
  "description": "",
  "mdms_number": "m56755",
  "license": "",
  "md5": "ca9bca68d33971977c3bec09cb3b874a",
  "rel_filepath": "./audio_cbcs_const_iv.mp4",
  "version": 1,
  "published": false,
  "associated_files": [],
  "features": [],
  "notes": "",
  "conforms_to": []
}
