=== MPEGGroup/FileFormatConformance/data/schemas/file-metadata.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Metadata scheme for contributed files",
  "type": "object",
  "properties": {
    "contributor": {
      "type": "string",
      "description": "Source of the file, e.g. company name"
    },
    "description": {
      "type": "string",
      "description": "Description of the file",
      "maxLength": 280
    },
    "md5": {
      "type": "string",
      "description": "MD5 checksum of the file"
    },
    "version": {
      "type": "integer",
      "description": "Version number of the file"
    },
    "published": {
      "type": "boolean",
      "default": false,
      "description": "Whether the file is published or not"
    },
    "associated_files": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^./.*$"
      },
      "description": "List of associated files"
    },
    "features": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "List of features as defined in the standard"
    },
    "notes": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "object"
        }
      ],
      "description": "Notes about the file"
    },
    "license": {
      "type": "string",
      "description": "License of the file"
    },
    "rel_filepath": {
      "type": "string",
      "pattern": "^./.*$",
      "description": "Relative path to the conformance file"
    },
    "mdms_number": {
      "anyOf": [
        { "type": "string", "pattern": "^m[0-9]+$" },
        {
          "type": "string",
          "maxLength": 0
        }
      ],
      "description": "MPEG Document Management System Number"
    },
    "conforms_to": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "ISO": {
            "type": "string",
            "description": "ISO number of the specification"
          },
          "version": {
            "type": "integer",
            "description": "Version of the specification"
          },
          "amendmends": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "minItems": 1
          },
          "corrigenda": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "minItems": 1
          }
        },
        "required": ["ISO", "version"]
      }
    }
  },
  "required": [
    "contributor",
    "description",
    "md5",
    "rel_filepath",
    "version",
    "published",
    "associated_files",
    "features",
    "license",
    "mdms_number",
    "conforms_to"
  ]
}

=== MPEGGroup/FileFormatConformance/data/file_features/under_consideration/cenc/image_cens_128iv.json
{
  "contributor": "Telecom Paris",
  "description": "",
  "mdms_number": "m56755",
  "license": "",
  "md5": "3147cb35e30dc800bed569205b777f10",
  "rel_filepath": "./image_cens_128iv.heic",
  "version": 1,
  "published": false,
  "associated_files": [],
  "features": [],
  "notes": "",
  "conforms_to": []
}

=== MPEGGroup/FileFormatConformance/data/file_features/under_consideration/heif_rgan_item_conformance/region-ellipse.json
{
  "contributor": "CANON Research Centre France",
  "description": "Ellipse region with 'udes' annotation.",
  "mdms_number": "m63203",
  "rel_filepath": "./region-ellipse.heic",
  "associated_files": [],
  "version": 1,
  "md5": "f52ecc1163fcac8a54e19b4ca706dd7d",
  "published": false,
  "features": [],
  "conforms_to": [],
  "notes": "",
  "license": ""
}

=== MPEGGroup/FileFormatConformance/data/file_features/under_consideration/cenc/image_cbcs_const_iv_roll.json
{
  "contributor": "Telecom Paris",
  "description": "",
  "mdms_number": "m56755",
  "license": "",
  "md5": "d0c7d1e737e4f53be5fa0b258ba3dfa6",
  "rel_filepath": "./image_cbcs_const_iv_roll.heic",
  "version": 1,
  "published": false,
  "associated_files": [],
  "features": [],
  "notes": "",
  "conforms_to": []
}

=== MPEGGroup/FileFormatConformance/data/file_features/published/heif/C004.json
{
  "contributor": "Nokia",
  "description": "10 image items sharing the same decoder configuration property.",
  "md5": "6fabdbba3d6ed39b860c291a04780e82",
  "version": 2,
  "published": true,
  "associated_files": [],
  "features": [],
  "notes": {
    "bitstreams": {
      "B036": {
        "commit": "f17e517f7518984b4450349a88edc09519082c74",
        "description": "HEVC Main profile encoded bitstream made up of 20 frames (1280x720 resolution)",
        "same_input_content": "B004",
        "url": "https://github.com/nokiatech/heif_conformance/blob/master/bitstreams/B036.265"
      }
    }
  },
  "license": "",
  "rel_filepath": "./C004.heic",
  "mdms_number": "m42431",
  "conforms_to": []
}

=== MPEGGroup/FileFormatConformance/data/file_features/published/nalu/l-hevc/shvc_hev1_lhe1_multiple_tracks_implicit.json
{
  "contributor": "Telecom ParisTech",
  "description": "L-HEVC Conformance (spatial and multiview layered)",
  "md5": "9cfe4a75265397c70dd378f63faa7567",
  "version": 1,
  "published": true,
  "associated_files": [],
  "features": ["video track", "Extractors", "Implicit Reconstruction"],
  "notes": "",
  "license": "",
  "rel_filepath": "./shvc_hev1_lhe1_multiple_tracks_implicit.mp4",
  "mdms_number": "",
  "conforms_to": []
}

=== MPEGGroup/FileFormatConformance/data/file_features/under_consideration/cenc/image_cenc_128iv.json
{
  "contributor": "Telecom Paris",
  "description": "",
  "mdms_number": "m56755",
  "license": "",
  "md5": "997dc996e49db3545f20e3ee618c3960",
  "rel_filepath": "./image_cenc_128iv.heic",
  "version": 1,
  "published": false,
  "associated_files": [],
  "features": [],
  "notes": "",
  "conforms_to": []
}

=== MPEGGroup/FileFormatConformance/data/file_features/published/isobmff/f1.json
{
  "contributor": "Fraunhofer IIS",
  "description": "Simple A/V",
  "md5": "6138df9c5b0dd2c2c3cae3b7408beb5d",
  "version": 1,
  "published": true,
  "associated_files": [],
  "features": ["Interleaved data", "IOD box", "mp4a sample entry"],
  "notes": "",
  "license": "",
  "rel_filepath": "./f1.mp4",
  "mdms_number": "",
  "conforms_to": []
}

=== MPEGGroup/FileFormatConformance/data/file_features/published/isobmff_nalu/nalu_updates/hevc_hvc1_hvc2_extractors_v2.json
{
  "contributor": "Telecom Paris / CANON Research Centre France",
  "description": "HEVC with temporal sub-layer using extractor and linf sample group description (hvc1/hvc2 tracks)",
  "mdms_number": "m64279",
  "rel_filepath": "./hevc_hvc1_hvc2_extractors_v2.mp4",
  "associated_files": [],
  "version": 1,
  "md5": "0b03b7e5aae77540deb85c373e4553cc",
  "published": false,
  "features": [],
  "conforms_to": [],
  "notes": "",
  "license": ""
}
